// Nexus provider definitions — matches exact OpenCode provider list

export interface ProviderDef {
  id: string;
  name: string;
  description: string;
  requiresKey: boolean;
  icon?: string;
  category?: string;
  apiStyle?: 'openai' | 'anthropic' | 'custom';
  defaultEndpoint?: string;
  authType?: 'api_key' | 'oauth' | 'token' | 'none';
  /** If true, user can select this provider as a direct API target */
  directConnect?: boolean;
  /** If set, shows a ▸ arrow indicating sub-options or multi-path */
  hasArrow?: boolean;
}

export const PROVIDER_DEFS: ProviderDef[] = [
  {
    id: 'nous-portal',
    name: 'Nous Portal',
    description: 'Everything your agent needs, 300+ models with bundled tool use',
    requiresKey: true,
    icon: '◈',
    category: 'recommended',
    apiStyle: 'openai',
    defaultEndpoint: 'https://portal.nousresearch.com/api/v1',
    authType: 'api_key',
    directConnect: true,
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    description: 'Pay-per-use API aggregator',
    requiresKey: true,
    icon: '◎',
    category: 'recommended',
    apiStyle: 'openai',
    defaultEndpoint: 'https://openrouter.ai/api/v1',
    authType: 'api_key',
    directConnect: true,
  },
  {
    id: 'novita',
    name: 'NovitaAI',
    description: 'Cloud: Model API, Agent Sandbox, GPU Cloud',
    requiresKey: true,
    icon: '◉',
    apiStyle: 'openai',
    defaultEndpoint: 'https://api.novita.ai/v3/openai',
    authType: 'api_key',
    directConnect: true,
  },
  {
    id: 'lm-studio',
    name: 'LM Studio',
    description: 'Local desktop app with built-in model server',
    requiresKey: false,
    icon: '◐',
    apiStyle: 'openai',
    defaultEndpoint: 'http://localhost:1234/v1',
    authType: 'none',
    directConnect: true,
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    description: 'Claude models via API key or Claude Code',
    requiresKey: true,
    icon: '◑',
    category: 'recommended',
    apiStyle: 'anthropic',
    defaultEndpoint: 'https://api.anthropic.com',
    authType: 'api_key',
    directConnect: true,
  },
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'Codex CLI or direct OpenAI API',
    requiresKey: true,
    icon: '◒',
    category: 'recommended',
    apiStyle: 'openai',
    defaultEndpoint: 'https://api.openai.com/v1',
    authType: 'api_key',
    directConnect: true,
    hasArrow: true,
  },
  {
    id: 'qwen',
    name: 'Qwen Cloud / DashScope',
    description: 'Qwen + multi-provider',
    requiresKey: true,
    icon: '◓',
    apiStyle: 'openai',
    defaultEndpoint: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    authType: 'api_key',
    directConnect: true,
  },
  {
    id: 'xai',
    name: 'xAI Grok',
    description: 'Direct API or SuperGrok / Premium+ OAuth',
    requiresKey: true,
    icon: '◔',
    apiStyle: 'openai',
    defaultEndpoint: 'https://api.x.ai/v1',
    authType: 'api_key',
    directConnect: true,
    hasArrow: true,
  },
  {
    id: 'xiaomi',
    name: 'Xiaomi MiMo',
    description: 'MiMo-V2.5 and V2 models: pro, omni, flash',
    requiresKey: true,
    icon: '◕',
    apiStyle: 'openai',
    authType: 'api_key',
    directConnect: true,
  },
  {
    id: 'tencent',
    name: 'Tencent TokenHub',
    description: 'Hy3 Preview via tokenhub.tencentmaas.com',
    requiresKey: true,
    icon: '◐',
    apiStyle: 'openai',
    defaultEndpoint: 'https://tokenhub.tencentmaas.com/api/v1',
    authType: 'api_key',
    directConnect: true,
  },
  {
    id: 'nvidia',
    name: 'NVIDIA NIM',
    description: 'Nemotron models via build.nvidia.com or local NIM',
    requiresKey: true,
    icon: '◕',
    category: 'recommended',
    apiStyle: 'openai',
    defaultEndpoint: 'https://integrate.api.nvidia.com/v1',
    authType: 'api_key',
    directConnect: true,
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    description: 'GitHub token API or copilot --acp process',
    requiresKey: true,
    icon: '◐',
    apiStyle: 'openai',
    authType: 'token',
    directConnect: true,
    hasArrow: true,
  },
  {
    id: 'huggingface',
    name: 'Hugging Face Inference Providers',
    description: 'HuggingFace Inference API',
    requiresKey: true,
    icon: '◕',
    apiStyle: 'openai',
    defaultEndpoint: 'https://api-inference.huggingface.co/v1',
    authType: 'api_key',
    directConnect: true,
  },
  {
    id: 'google',
    name: 'Google Gemini',
    description: 'AI Studio API or OAuth + Code Assist',
    requiresKey: true,
    icon: '◑',
    category: 'recommended',
    apiStyle: 'openai',
    defaultEndpoint: 'https://generativelanguage.googleapis.com/v1beta/openai',
    authType: 'api_key',
    directConnect: true,
    hasArrow: true,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    description: 'V3, R1, coder, direct API',
    requiresKey: true,
    icon: '◒',
    category: 'recommended',
    apiStyle: 'openai',
    defaultEndpoint: 'https://api.deepseek.com/v1',
    authType: 'api_key',
    directConnect: true,
  },
  {
    id: 'zai',
    name: 'Z.AI / GLM',
    description: 'Zhipu direct API',
    requiresKey: true,
    icon: '◓',
    apiStyle: 'openai',
    authType: 'api_key',
    directConnect: true,
  },
  {
    id: 'kimi',
    name: 'Kimi / Moonshot',
    description: 'Coding Plan, Moonshot global & China endpoints',
    requiresKey: true,
    icon: '◔',
    apiStyle: 'openai',
    defaultEndpoint: 'https://api.moonshot.cn/v1',
    authType: 'api_key',
    directConnect: true,
    hasArrow: true,
  },
  {
    id: 'stepfun',
    name: 'StepFun Step Plan',
    description: 'Agent / coding models via Step Plan API',
    requiresKey: true,
    icon: '◕',
    apiStyle: 'openai',
    authType: 'api_key',
    directConnect: true,
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    description: 'Global, OAuth Coding Plan & China endpoints',
    requiresKey: true,
    icon: '◐',
    apiStyle: 'openai',
    authType: 'api_key',
    directConnect: true,
    hasArrow: true,
  },
  {
    id: 'ollama-cloud',
    name: 'Ollama Cloud',
    description: 'Cloud-hosted open models, ollama.com',
    requiresKey: true,
    icon: '◑',
    apiStyle: 'openai',
    defaultEndpoint: 'https://api.ollama.com/v1',
    authType: 'api_key',
    directConnect: true,
  },
  {
    id: 'arcee',
    name: 'Arcee AI',
    description: 'Trinity models, direct API',
    requiresKey: true,
    icon: '◒',
    apiStyle: 'openai',
    authType: 'api_key',
    directConnect: true,
  },
  {
    id: 'gmi',
    name: 'GMI Cloud',
    description: 'Multi-model direct API',
    requiresKey: true,
    icon: '◓',
    apiStyle: 'openai',
    authType: 'api_key',
    directConnect: true,
  },
  {
    id: 'kilo',
    name: 'Kilo Code',
    description: 'Kilo Gateway API',
    requiresKey: true,
    icon: '◔',
    apiStyle: 'openai',
    authType: 'api_key',
    directConnect: true,
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    description: 'Zen pay-as-you-go or Go subscription',
    requiresKey: true,
    icon: '◕',
    apiStyle: 'openai',
    authType: 'api_key',
    directConnect: true,
    hasArrow: true,
  },
  {
    id: 'bedrock',
    name: 'AWS Bedrock',
    description: 'Claude, Nova, Llama, DeepSeek; IAM or API key',
    requiresKey: true,
    icon: '◐',
    apiStyle: 'openai',
    authType: 'api_key',
    directConnect: true,
  },
  {
    id: 'azure',
    name: 'Azure Foundry',
    description: 'OpenAI-style or Anthropic-style endpoint, your Azure AI deployment',
    requiresKey: true,
    icon: '◑',
    apiStyle: 'openai',
    authType: 'api_key',
    directConnect: true,
  },
  {
    id: 'qwen-oauth',
    name: 'Qwen OAuth',
    description: 'Reuses local Qwen CLI login',
    requiresKey: false,
    icon: '◒',
    apiStyle: 'openai',
    authType: 'oauth',
    directConnect: true,
  },
  {
    id: 'alibaba',
    name: 'Alibaba Cloud Coding Plan',
    description: 'Dedicated coding tier',
    requiresKey: true,
    icon: '◓',
    apiStyle: 'openai',
    authType: 'api_key',
    directConnect: true,
  },
  {
    id: 'custom',
    name: 'custom',
    description: 'direct API',
    requiresKey: false,
    icon: '◔',
    apiStyle: 'custom',
    authType: 'none',
    directConnect: true,
  },
  {
    id: 'local-ollama',
    name: 'Local Ollama',
    description: 'openrouter.ai/api/v1 — nvidia/nemotron-3-super-120b-a12b:free',
    requiresKey: false,
    icon: '◕',
    apiStyle: 'openai',
    defaultEndpoint: 'http://localhost:11434/v1',
    authType: 'none',
    directConnect: true,
  },
  {
    id: 'custom-endpoint',
    name: 'Custom endpoint',
    description: 'enter URL manually',
    requiresKey: false,
    icon: '◐',
    apiStyle: 'custom',
    authType: 'none',
    directConnect: true,
  },
  {
    id: 'ollama',
    name: 'Ollama (local)',
    description: 'Auto-detected at localhost:11434',
    requiresKey: false,
    icon: '◑',
    apiStyle: 'openai',
    defaultEndpoint: 'http://localhost:11434/v1',
    authType: 'none',
    directConnect: true,
  },
];

/** System meta-options that are not real providers */
export const META_OPTIONS = [
  {
    id: '__remove_custom',
    name: 'Remove a saved custom provider',
    icon: '✕',
  },
  {
    id: '__configure_aux',
    name: 'Configure auxiliary models...',
    icon: '⚙',
  },
  {
    id: '__leave_unchanged',
    name: 'Leave unchanged',
    icon: '—',
  },
];
